### ISSUE TITLE
Can not use the plugin.

### ISSUE THREAD

**Issue by hugo-sna** [jasonjgardner/fresh_tailwind#4]
I'm having a problem trying to use the plugin, it simply doesn't work. when I add it using
`fresh.config.ts`
```ts
import { defineConfig } from "$fresh/server.ts";
import tailwindPlugin from "https://deno.land/x/fresh_tailwind@v0.2.1/mod.ts";

export default defineConfig({
  plugins: [
    tailwindPlugin(),
  ],
});
```
It gives me this error:
```
error: Relative import path "tailwindcss" not prefixed with / or ./ or ../ and not in import map from "https://deno.land/x/fresh_tailwind@v0.2.1/mod.ts"
    at https://deno.land/x/fresh_tailwind@v0.2.1/mod.ts:14:22
```
I'm using this version of deno
```
deno 1.37.2 (release, x86_64-pc-windows-msvc)      
v8 11.8.172.13
typescript 5.2.2
fresh: 1.5.2
```

**Comment by hugo-sna** [comment]
I've tried to fix it myself but I couldn't, I don't really where `tailwind` and post `postcss` are

**Comment by jasonjgardner** [comment]
Oh right – I forgot a crucial step. These need to be defined in your project's `deno.json` file, or in the import map. Quick fix is to copy those lines from this file: https://github.com/jasonjgardner/fresh_tailwind/blob/b062ab064c5688dbd2faab56686b99045dc23f99/deno.json

I will create a `deps.ts` file so this is _actually_ zero-config. Thanks for bringing this to my attention!
