### ISSUE TITLE
What does main.ts do?

### ISSUE THREAD

**Issue by hugo-sna** [jasonjgardner/fresh_tailwind#8]
I'm trying to fix build loops in my project but I don't really understand what `deno run --allow-read --allow-write --allow-env --config=./deno.json https://deno.land/x/fresh_tailwind/main.ts` does, can you explain?

**Comment by jasonjgardner** [comment]
The purpose of `main.ts` is to act as an entrypoint for CLI usage. It can be used to build or install Tailwind from a `deno run` command.

Previously, the only purpose was to ensure the CSS output would be saved in your `./static` directory.

(You may need to remove the CSS output directory from your watched paths if you're experiencing refresh loops.)
