### ISSUE TITLE
Does not work in production,

### ISSUE THREAD

**Issue by hugo-sna** [jasonjgardner/fresh_tailwind#9]
The style doesn't apply on some pages when using `deno task preview`

**Comment by jasonjgardner** [comment]
You'll want to pre-build your CSS for production. Using the plugin with `deno task build` will output a CSS file, which you can then use in a `<link rel="stylesheet" />` tag somewhere in your `<head>`.

Check out this new documentation for more build options: https://github.com/jasonjgardner/fresh_tailwind/tree/988e8608961692552a79e515ad1767a70478819f?tab=readme-ov-file#setup-ahead-of-time-builds
